# Generated by Django 4.0.3 on 2022-04-19 00:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteLm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(default='', max_length=30, unique=True)),
                ('customer_id', models.CharField(choices=[('', 'Name...'), ('Boeing Canada', 'Boeing Canada'), ('Boeing Seattle', 'Boeing Seattle'), ('Boeing St.Louis', 'Boeing St.Louis'), ('L3 Harris', 'L3 Harris'), ('Lockheed Martin', 'Lockheed Martin'), ('Northrop Grumman', 'Northrop Grumman'), ('Sikorsky', 'Sikorsky'), ('Spirit', 'Spirit')], default='', max_length=30)),
                ('date', models.DateField(default=datetime.date(2022, 4, 19))),
                ('length', models.PositiveIntegerField(default='')),
                ('width', models.PositiveIntegerField(default='')),
                ('height', models.PositiveIntegerField(default='')),
                ('material', models.CharField(choices=[('', 'Type...'), ('AL', 'Aluminum'), ('STL', 'Steel'), ('INV', 'Invar')], default='', max_length=10)),
                ('surface_finish', models.CharField(choices=[('', 'Type...'), ('32RA', '32 Ra'), ('64RA', '64 Ra'), ('125RA', '125 Ra')], default='', max_length=10)),
                ('h_headers', models.PositiveIntegerField(default='')),
                ('v_headers', models.PositiveIntegerField(default='')),
                ('bubs_num', models.PositiveIntegerField(default='')),
                ('drill_bar_num', models.PositiveIntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(blank=True, default='', max_length=30)),
                ('customer_id', models.CharField(blank=True, choices=[('', 'Name...'), ('Boeing Canada', 'Boeing Canada'), ('Boeing Seattle', 'Boeing Seattle'), ('Boeing St.Louis', 'Boeing St.Louis'), ('L3 Harris', 'L3 Harris'), ('Lockheed Martin', 'Lockheed Martin'), ('Northrop Grumman', 'Northrop Grumman'), ('Sikorsky', 'Sikorsky'), ('Spirit', 'Spirit')], default='', max_length=30)),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalcPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weld_price', models.PositiveIntegerField(default='')),
                ('fit_price', models.PositiveIntegerField(default='')),
                ('program_price', models.PositiveIntegerField(default='')),
                ('machine_price', models.PositiveIntegerField(default='')),
                ('bench_price', models.PositiveIntegerField(default='')),
                ('assembly_price', models.PositiveIntegerField(default='')),
                ('shipping_price', models.PositiveIntegerField(default='')),
                ('laser_price', models.PositiveIntegerField(default='')),
                ('inspect_price', models.PositiveIntegerField(default='')),
                ('total_price', models.PositiveIntegerField(default='')),
                ('quote_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quote_lm.quotelm')),
            ],
        ),
        migrations.CreateModel(
            name='CalcHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weld_hours', models.PositiveIntegerField(default='')),
                ('fit_hours', models.PositiveIntegerField(default='')),
                ('program_hours', models.PositiveIntegerField(default='')),
                ('machine_hours', models.PositiveIntegerField(default='')),
                ('bench_hours', models.PositiveIntegerField(default='')),
                ('assembly_hours', models.PositiveIntegerField(default='')),
                ('shipping_hours', models.PositiveIntegerField(default='')),
                ('laser_hours', models.PositiveIntegerField(default='')),
                ('inspect_hours', models.PositiveIntegerField(default='')),
                ('total_hours', models.PositiveIntegerField(default='')),
                ('quote_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='quote_lm.quotelm')),
            ],
        ),
    ]
