# Generated by Django 4.0.3 on 2022-03-21 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_lm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotelm',
            name='text',
        ),
        migrations.AddField(
            model_name='quotelm',
            name='bubs_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='customer_id',
            field=models.CharField(choices=[('', 'Name...'), ('BC', 'Boeing Canada'), ('BS', 'Boeing Seattle'), ('BL', 'Boeing St.Louis'), ('L3', 'L3 Harris'), ('LM', 'Lockheed Martin'), ('NG', 'Northrop Grumman'), ('SK', 'Sikorsky'), ('SP', 'Spirit')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 21)),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='drill_bar_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='h_headers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='height',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='length',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='material',
            field=models.CharField(choices=[('', 'Type...'), ('AL', 'Aluminum'), ('STL', 'Steel'), ('INV', 'Invar')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='quote_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='surface_finish',
            field=models.CharField(choices=[('', 'Type...'), ('32RA', '32 Ra'), ('64RA', '64 Ra'), ('125RA', '125 Ra')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='v_headers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotelm',
            name='width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
