# Generated by Django 4.0.3 on 2022-03-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_lm', '0002_remove_quotelm_text_quotelm_bubs_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelm',
            name='bubs_num',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='quotelm',
            name='drill_bar_num',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='quotelm',
            name='h_headers',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='quotelm',
            name='height',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='quotelm',
            name='length',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='quotelm',
            name='v_headers',
            field=models.PositiveIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='quotelm',
            name='width',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
