# Generated by Django 4.0.3 on 2022-03-22 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_lm', '0003_alter_quotelm_bubs_num_alter_quotelm_drill_bar_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotelm',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 22)),
        ),
    ]
